
package presentacion;

import java.awt.event.ActionListener;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.sound.sampled.Clip;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;


import negocio.NegocioEmisor;
import negocio.Mensaje;
import negocio.Persona;
import negocio.NegocioReceptor;

public class VentanaReceptor extends javax.swing.JFrame implements IVentanaReceptor {
	
        private DefaultListModel<Mensaje> listaRecibidos;
	private Clip clip;
	
    /** Creates new form VentanaReceptor */
    public VentanaReceptor() {
        this.listaRecibidos = new DefaultListModel<Mensaje>();
        
        initComponents();
        this.botonAbrir.setActionCommand("ABRIR MENSAJE");
        this.cerrarMensaje.setActionCommand("CERRAR MENSAJE");
        this.botonPararAlerta.setActionCommand("PARAR ALERTA");
        this.btConfirmarReceptor.setActionCommand("ACEPTAR SESION");
        this.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent e) {
                NegocioReceptor.getInstancia().notificarDesconexionDirectorio();
                        System.exit(0);
                    }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    private void initComponents() {//GEN-BEGIN:initComponents

        jDialog1 = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        labelDestinatario = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        cerrarMensaje = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        asuntoMsjRecibido = new javax.swing.JTextPane();
        jPanel11 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoMsjRecibido = new javax.swing.JTextPane();
        jOptionPane1 = new javax.swing.JOptionPane();
        jdiagAlertaSonora = new javax.swing.JDialog();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        botonPararAlerta = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jDiagSesionRecep = new javax.swing.JDialog();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        nombreReceptor = new javax.swing.JTextArea();
        jPanel26 = new javax.swing.JPanel();
        btConfirmarReceptor = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMensajesRecibidos = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        botonAbrir = new javax.swing.JButton();

        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setLayout(new java.awt.GridLayout(3, 0));

        jPanel17.setLayout(new java.awt.GridLayout(1, 2));

        jPanel18.setLayout(new java.awt.GridLayout(1, 0));

        labelDestinatario.setText("De: Ivan Aprea");
        jPanel18.add(labelDestinatario);

        jPanel17.add(jPanel18);

        jPanel19.setLayout(new java.awt.GridLayout(1, 0));
        jPanel17.add(jPanel19);

        jPanel10.add(jPanel17);

        jPanel12.setLayout(new java.awt.GridLayout(1, 2));

        jLabel2.setText("Asunto");
        jPanel12.add(jLabel2);

        cerrarMensaje.setText("Cerrar");
        jPanel16.add(cerrarMensaje);

        jPanel12.add(jPanel16);

        jPanel10.add(jPanel12);

        jPanel13.setLayout(new java.awt.BorderLayout());

        asuntoMsjRecibido.setText("Hola");
        jScrollPane2.setViewportView(asuntoMsjRecibido);

        jPanel13.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel13);

        jPanel9.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setText("Mensaje");
        jPanel14.add(jLabel3);

        jPanel11.add(jPanel14, java.awt.BorderLayout.PAGE_START);

        jPanel15.setLayout(new java.awt.BorderLayout());

        textoMsjRecibido.setText("Hola, como va?");
        jScrollPane3.setViewportView(textoMsjRecibido);

        jPanel15.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel15, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel11, java.awt.BorderLayout.CENTER);

        jDialog1.getContentPane().add(jPanel9, java.awt.BorderLayout.CENTER);

        jOptionPane1.setToolTipText("");

        jPanel20.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mensaje entrante");
        jPanel21.add(jLabel4);

        jPanel20.add(jPanel21, java.awt.BorderLayout.PAGE_START);

        botonPararAlerta.setText("Parar");
        jPanel22.add(botonPararAlerta);

        jPanel20.add(jPanel22, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        jPanel20.add(jPanel23, java.awt.BorderLayout.CENTER);

        jdiagAlertaSonora.getContentPane().add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel24.setLayout(new java.awt.GridLayout(2, 2));

        jPanel25.setLayout(new java.awt.GridLayout(2, 0));

        jLabel6.setText("Iniciar Sesion");
        jPanel27.add(jLabel6);

        jPanel25.add(jPanel27);

        jLabel5.setText("Nombre");
        jPanel28.add(jLabel5);

        jPanel25.add(jPanel28);

        jPanel24.add(jPanel25);

        jPanel32.setLayout(new java.awt.GridLayout(2, 0));

        nombreReceptor.setColumns(20);
        nombreReceptor.setRows(5);
        jScrollPane4.setViewportView(nombreReceptor);

        jPanel34.add(jScrollPane4);

        jPanel32.add(jPanel34);

        btConfirmarReceptor.setText("Confirmar");
        jPanel26.add(btConfirmarReceptor);

        jPanel32.add(jPanel26);

        jPanel24.add(jPanel32);

        jDiagSesionRecep.getContentPane().add(jPanel24, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mensajes recibidos");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        listaMensajesRecibidos.setModel(this.listaRecibidos);
        listaMensajesRecibidos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaMensajesRecibidos);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setPreferredSize(new java.awt.Dimension(592, 75));
        jPanel4.setLayout(new java.awt.GridLayout(1, 4));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridBagLayout());
        jPanel4.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridBagLayout());

        botonAbrir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonAbrir.setText("Abrir");
        jPanel8.add(botonAbrir, new java.awt.GridBagConstraints());

        jPanel4.add(jPanel8);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    
    public Clip getClip() {
                return this.clip;
        }

        public void setClip(Clip clip) {
                this.clip = clip;
        }

    public void abrirMensaje() {
        if(listaMensajesRecibidos.getSelectedValue()!= null) {
            this.actualizaMensajeAbierto(
                        listaMensajesRecibidos.getSelectedValue().getEmisor(),
                        listaMensajesRecibidos.getSelectedValue().getAsunto(),
                        listaMensajesRecibidos.getSelectedValue().getTexto());
            this.jDialog1.setSize(400, 400);
            this.jDialog1.setVisible(true);
            this.repaint();
        }
    }
    
    public void iniciarSesion() {
        this.jDiagSesionRecep.setSize(400, 400);
        this.jDiagSesionRecep.setVisible(true);
        this.nombreReceptor.setText(NegocioReceptor.getInstancia().getNombre());
        this.repaint();
    }
    
    public void confirmarSesion() {
        String nombre = this.nombreReceptor.getText().trim();
        if(!nombre.equals(""))
                {
            NegocioReceptor.getInstancia().configAtributos(nombre);
                    this.jDiagSesionRecep.setVisible(false);
            NegocioReceptor.getInstancia().iniciarSesion();
                }
                else {
                        this.lanzarCartelError("ERROR: debe completar todos los campos");
                }
    }
    
    public void mostrarVentana(){
        this.setVisible(true);
        this.repaint();
    }
    
    public void lanzarAlerta(String emisor) {
        this.jLabel4.setText("Mensaje entrante de: "+emisor);
        this.jdiagAlertaSonora.pack();
        this.jdiagAlertaSonora.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        this.jdiagAlertaSonora.setVisible(true);
        this.clip.start();
        this.repaint();
    }
    
    public void cerrarMensaje() {
        this.jDialog1.setVisible(false);
    }
    
    public void pararAlerta() {
        this.clip.stop();
        this.jdiagAlertaSonora.setVisible(false);
    }
    
    public void actualizaListaMensajes(Mensaje mensaje)
    {
        this.listaRecibidos.addElement(mensaje);
        this.repaint();
    }
    
    public void lanzarCartelError(String err) {
        JOptionPane.showMessageDialog(null, err);
    }
    
    public void actualizaMensajeAbierto(Persona emisorAct, String asuntoAct, String textoAct)
    {
        this.textoMsjRecibido.setText(textoAct);
        this.asuntoMsjRecibido.setText(asuntoAct);
        this.labelDestinatario.setText("De: "+emisorAct.getNombre());
    }

    public JDialog getJDiagSesionRecep() {
        return jDiagSesionRecep;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane asuntoMsjRecibido;
    private javax.swing.JButton botonAbrir;
    private javax.swing.JButton botonPararAlerta;
    private javax.swing.JButton btConfirmarReceptor;
    private javax.swing.JButton cerrarMensaje;
    private javax.swing.JDialog jDiagSesionRecep;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JDialog jdiagAlertaSonora;
    private javax.swing.JLabel labelDestinatario;
    private javax.swing.JList<Mensaje> listaMensajesRecibidos;
    private javax.swing.JTextArea nombreReceptor;
    private javax.swing.JTextPane textoMsjRecibido;
    // End of variables declaration//GEN-END:variables

    @Override
            public void addActionListener(ActionListener actionListener) {
                    this.botonAbrir.addActionListener(actionListener);
                    this.cerrarMensaje.addActionListener(actionListener);
                    this.botonPararAlerta.addActionListener(actionListener);
                    this.btConfirmarReceptor.addActionListener(actionListener);
                    
            }

}
